spring:      
  datasource:
    url: jdbc:mysql://localhost:3306/testdb?useSSL=false
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop #create-drop enable it if need to create DDL for the first time
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect